name: Publish to JetBrains Marketplace

on:
  push:

concurrency:
  group: publish-plugin-${{ github.ref_name }}
  cancel-in-progress: true


jobs:
  test:
    name: Run Tests for ${{ matrix.environmentName }}
    runs-on: arc-runners-small
    timeout-minutes: 60
    strategy:
      matrix:
        environmentName:
          - 251
          - 252
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version-file: '.java-version'
          distribution: 'corretto'

      - name: Run Tests
        run: |
          echo "environmentName=${{ matrix.environmentName }}"
          ./gradlew test --no-daemon -PenvironmentName=$environmentName

  verify:
    name: Verify Plugin for ${{ matrix.environmentName }}
    runs-on: arc-runners-small
    timeout-minutes: 60
    strategy:
      matrix:
        environmentName:
          - 251
          - 252
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version-file: '.java-version'
          distribution: 'corretto'

      - name: Verify Plugin
        run: |
          echo "environmentName=${{ matrix.environmentName }}"
          ./gradlew verifyPlugin --no-daemon -PenvironmentName=$environmentName

#  publish:
#    name: Publish Plugin
#    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#    runs-on: arc-runners-small
#    needs:
#      - test
#      - verify
#    timeout-minutes: 30
#    steps:
#      - uses: actions/checkout@v4
#
#      - uses: actions/setup-java@v4
#        with:
#          java-version-file: '.java-version'
#          distribution: 'corretto'
#
#      - name: Publish Plugin
#        run: |
#          ./gradlew publishPlugin --no-daemon
#        env:
#          JB_MARKETPLACE_TOKEN: ${{ secrets.JB_MARKETPLACE_TOKEN }}
